# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - myexpenses-func

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.12'
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Setup Python version
          uses: actions/setup-python@v5
          with:
            python-version: ${{ env.PYTHON_VERSION }}
          
        - name: 'Resolve project dependencies using Pip'
          run: |
            python -m venv .venv
            source .venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
        - name: 'Login to Azure'
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_266AE24A08A84ECBB8228796EC7BCF59 }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CCA5575116C34D199DDAAC5C91C27F5C }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F5BC864E89C14A2BA021371589BF45F6 }}
            
        - name: 'Deploy to Azure Functions'
          uses: Azure/functions-action@v1
          id: deploy-to-function
          with:
            app-name: 'myexpenses-func'
            slot-name: 'Production'
            package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
            publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
            clean: 'true'
            scm-do-build-during-deployment: 'true'


